// business-data.ts — auto-generated by generate.mjs, do not edit by hand

export interface MenuItem {
  name: string
  desc: string
  price: string
  pair?: string
  image?: string
}

export interface Review {
  name: string
  text: string
  rating?: number
}

export interface MenuSection {
  title: string
  icon: 'Flame' | 'UtensilsCrossed' | 'Sparkles'
  items: MenuItem[]
}

export interface HeroStat {
  val: string
  label: string
  stars?: boolean
}

export interface GalleryItem {
  gradient?: string
  emoji?: string
  icon?: string
  image?: string
  title: string
  sub?: string
}

export interface WhyChooseItem {
  icon: 'Timer' | 'ThumbsUp' | 'Shield' | 'Award'
  text: string
}

export interface AboutStat {
  value: string
  label: string
}

export interface HoursDetail {
  wedFri: string
  saturday: string
  sunday: string
  closedDays: string
}

export interface BusinessData {
  template: string

  // Basic info
  name: string
  subtitle: string
  tagline: string
  established: string
  location: string
  street: string
  postcode: string
  phone: string
  email: string
  googleRating: string
  googleReviews: string

  // Hero
  heroLine1: string
  heroLine2: string
  heroBadge: string
  heroStats: HeroStat[]

  // Certifications
  certifications: string[]

  // Menu
  menuSections: MenuSection[]
  menuIntroTitle: string
  menuIntroText: string

  // About
  aboutTitle: string
  aboutSubtitle: string
  aboutParagraphs: string[]
  aboutStats: AboutStat[]
  whyChooseItems: WhyChooseItem[]

  // Gallery
  galleryItems: GalleryItem[]

  // Reviews
  reviews: Review[]

  // Reservation
  reservationIntro: string
  reservationNote: string
  occasionOptions: string[]

  // Footer
  footerNote: string
  hoursDetail: HoursDetail

  // CTA
  heroCta1: { text: string; href: string }
  heroCta2: { text: string; href: string }

  // Info ticker
  infoTicker: Array<{ icon: 'MapPin' | 'Clock' | 'Phone' | 'Wine'; text: string }>

  // SEO / Meta
  pageTitle: string

  // Socials
  instagram?: string
  facebook?: string
  twitter?: string
}

export const businessData: BusinessData = {
  template: 'restaurant',

  name: 'Noir',
  subtitle: 'Fine Dining',
  tagline: 'An intimate 24-seat dining room in a Grade II listed building. Three tasting menus. One unforgettable evening.',
  established: '2014',
  location: 'Bath, UK',
  street: '17 Royal Crescent, Bath BA1 2LR',
  postcode: 'BA1 2LR',
  phone: '+44 1225 123456',
  email: 'reservations@noirbath.co.uk',
  googleRating: '4.9',
  googleReviews: '340+ reviews',

  heroLine1: 'Noir',
  heroLine2: 'FINE DINING',
  heroBadge: 'Michelin Recommended',

  heroStats: [
    { val: 'AA', label: 'Rosette Award' },
    { val: '4.9', label: 'Google Rating', stars: true },
    { val: '24', label: 'Seats Only' },
    { val: '2014', label: 'Established' },
  ],

  certifications: ['AA Rosette', 'Michelin Recommended', 'Good Food Guide'],

  menuSections: [
    {
      title: 'To Start',
      icon: 'Flame',
      items: [
        { name: 'Seared Scallop', desc: 'Celeriac purée, brown butter, apple, hazelnut crumb', price: '18', pair: 'Chablis Premier Cru' },
        { name: 'Beef Tartare', desc: 'Hand-cut fillet, cured yolk, caper, smoked bone marrow, sourdough', price: '19', pair: 'Barolo 2018' },
        { name: 'Roasted Beetroot', desc: 'Goat curd, candied walnut, blood orange, aged balsamic', price: '14', pair: 'Sancerre Rosé' },
      ],
    },
    {
      title: 'Main Course',
      icon: 'UtensilsCrossed',
      items: [
        { name: 'Dry-Aged Ribeye', desc: '40-day aged, pomme purée, grilled hispi cabbage, peppercorn sauce', price: '42', pair: 'Châteauneuf-du-Pape' },
        { name: 'Pan-Roasted Halibut', desc: 'Jerusalem artichoke, brown shrimp butter, samphire, lemon', price: '34', pair: 'White Burgundy' },
        { name: 'Truffle Risotto', desc: 'Carnaroli rice, winter truffle, aged Parmesan, wild mushroom', price: '28', pair: "Barbera d'Alba" },
        { name: 'Lamb Rack', desc: 'Herb-crusted, ratatouille, rosemary jus, confit garlic', price: '38', pair: 'Bordeaux Supérieur' },
      ],
    },
    {
      title: 'To Finish',
      icon: 'Sparkles',
      items: [
        { name: 'Dark Chocolate Tart', desc: 'Salted caramel, crème fraîche, gold leaf, cocoa tuile', price: '14', pair: 'Tawny Port' },
        { name: 'Vanilla Panna Cotta', desc: 'Poached rhubarb, ginger crumble, white chocolate snow', price: '12', pair: "Moscato d'Asti" },
      ],
    },
  ],
  menuIntroTitle: 'A Journey Through Taste',
  menuIntroText: 'Three courses. Optional wine pairing. Ingredients sourced within 30 miles.',

  aboutTitle: 'Three Generations',
  aboutSubtitle: 'of Passion',
  aboutParagraphs: [
    'Since 2014, Noir has been the intimate jewel of Bath\'s dining scene — a 24-seat room where every table is the best table.',
    'Our kitchen is led by Chef Marcus Delacour, who trained under three Michelin-starred chefs before returning to his Somerset roots.',
    'We work directly with 14 local farms and foragers across the West Country, changing our tasting menus every six weeks to follow the seasons.',
  ],
  aboutStats: [
    { value: '10+', label: 'Years' },
    { value: '300+', label: 'Wine Labels' },
    { value: '4.9', label: 'Google Rating' },
  ],
  whyChooseItems: [
    { icon: 'Award', text: 'AA Rosette awarded every year since opening' },
    { icon: 'Timer', text: 'Ingredients delivered within 6 hours of harvest' },
    { icon: 'ThumbsUp', text: '98% guest satisfaction across 1,200+ reviews' },
    { icon: 'Shield', text: 'Every dietary requirement catered with confidence' },
  ],

  galleryItems: [
    { gradient: 'from-amber-900/80 via-amber-700/60 to-amber-900/80', emoji: '🍷', title: 'The Cellar' },
    { gradient: 'from-stone-800/80 via-stone-700/60 to-stone-800/80', emoji: '🔥', title: 'The Grill' },
    { gradient: 'from-zinc-800/80 via-zinc-700/50 to-zinc-800/80', emoji: '🍝', title: 'The Kitchen' },
    { gradient: 'from-amber-800/80 via-yellow-700/50 to-amber-800/80', emoji: '🕯️', title: 'The Terrace' },
    { gradient: 'from-stone-900/80 via-amber-800/50 to-stone-900/80', emoji: '🧀', title: 'The Pantry' },
    { gradient: 'from-zinc-900/80 via-amber-700/40 to-zinc-900/80', emoji: '🥂', title: 'The Bar' },
  ],

  reviews: [
    { name: 'Charlotte Wells', text: 'Perhaps the finest dining experience in the county. The ribeye was transcendental — worth every penny and every mile.', rating: 5 },
    { name: 'Marco Bellini', text: 'As a chef, I rarely praise other kitchens. But Noir deserves every accolade. The scallop dish changed how I think about shellfish.' },
    { name: 'The Harrisons', text: 'Took my wife for our anniversary. They remembered her name, her favourite wine, and even the table we sat at three years ago.', rating: 5 },
  ],

  reservationIntro: 'We recommend booking at least 48 hours in advance for weekend dining.',
  reservationNote: 'We release tables 90 days in advance. Weekend slots typically fill within 48 hours.',
  occasionOptions: ['Anniversary', 'Birthday', 'Business', 'Just Because'],

  footerNote: 'Dress code: Smart casual. No sportswear please.',
  hoursDetail: {
    wedFri: '18:00—23:00',
    saturday: '17:30—23:00',
    sunday: '12:30—21:00',
    closedDays: 'Mon—Tue · Closed',
  },

  heroCta1: { text: 'View Our Menus', href: '#menu' },
  heroCta2: { text: 'Book a Table', href: '#reserve' },

  infoTicker: [
    { icon: 'MapPin', text: '17 Royal Crescent, Bath' },
    { icon: 'Clock', text: 'Wed—Sun · 18:00—23:00' },
    { icon: 'Phone', text: '+44 1225 123456' },
    { icon: 'Wine', text: '300+ Wine List' },
  ],

  pageTitle: 'Noir — Fine Dining Restaurant in Bath',

  instagram: '#',
  facebook: '#',
  twitter: '#',
} as const
